version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/database:/usr/src/app/database
    environment:
      - NODE_ENV=development
      - PORT=3002
      - JWT_SECRET=embsecret2025
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped